version: 2.1 # Use version 2.1 to enable orb usage.

orbs:
  win: circleci/windows@2.2.0 # The Windows orb give you everything you need to start using the Windows executor.

jobs:
  build: # name of your job
    executor:
      name: win/default # executor type

    steps:
      - run:
          - command: Set-Variable -Name CMAKE_URL -Value "https://github.com/Kitware/CMake/releases/download/v3.17.0-rc1/cmake-3.17.0-rc1-win64-x64.zip"
          - shell: powershell.exe
      - run:
          - command: Set-Variable -Name CWD -Value $(Get-Location)
          - shell: powershell.exe
      - run:
          - command: Set-Variable -Name CMAKE_DIR -Value "$cwd\cmake"
          - shell: powershell.exe
      - run:
          - command: $WebClient = New-Object System.Net.WebClient ; WebClient.DownloadFile($CMAKE_URL, $CMAKE_DIR)
          - shell: powershell.exe
      - run:
          - command: Expand-Archive .\cmake-3.17.0-rc1-win64-x64.zip -DestinationPath cmake
          - shell: powershell.exe
      - run:
          - command: $Env:Path += "$CMAKE_DIR\cmake-3.17.0-rc1-win64-x64\bin"
      - run:
          - command:
      - checkout
      - run:
          command: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug ..
          shell: bash.exe
      - run:
          command: cmake -G "Visual Studio 16 2019" ..
          shell: bash.exe
      - run:
          command: devenv ACrossPlatformCppLibrary.sln /Build
          shell: cmd.exe
      - run:
          command: cd test\Debug
          shell: cmd.exe
      - run:
          command: text.exe
          shell: cmd.exe
