version: 2.1 # Use version 2.1 to enable orb usage.

orbs:
  win: circleci/windows@2.2.0 # The Windows orb give you everything you need to start using the Windows executor.

jobs:
  build: # name of your job
    executor:
      name: win/default # executor type

    steps:
      - run:
          - command:
      - checkout
      - run:
          command: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug ..
          shell: bash.exe
      - run:
          command: cmake -G "Visual Studio 16 2019" ..
          shell: bash.exe
      - run:
          command: devenv ACrossPlatformCppLibrary.sln /Build
          shell: cmd.exe
      - run:
          command: cd test\Debug
          shell: cmd.exe
      - run:
          command: text.exe
          shell: cmd.exe
