version: 2.1 # Use version 2.1 to enable orb usage.

orbs:
  win: circleci/windows@2.2.0 # The Windows orb give you everything you need to start using the Windows executor.

jobs:
  build-win: # name of your job
    executor: win/default # executor type

    steps:
      - run:
          - command: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug ..
          - shell: bash.exe
      - run:
          - command: cmake -G "Visual Studio 16 2019" ..
          - shell: bash.exe
      - run:
          - devenv ACrossPlatformCppLibrary.sln /Build
          - shell: cmd.exe
