version: 2.1 # Use version 2.1 to enable orb usage.

orbs:
  win: circleci/windows@2.2.0 # The Windows orb give you everything you need to start using the Windows executor.

jobs:
  build: # name of your job
    executor:
      name: win/default # executor type
    steps:
      - run:
          name: "Build windows"
          command: |
            git clone https://github.com/CiaranWelsh/ACrossPlatformCppLibrary.git
            cd ACrossPlatformCppLibrary
            ls
            & build_powershell.ps1
          shell: powershell.exe
#      - run:
#          command: cd ACrossPlatformCppLibrary
#          shell: powershell.exe
#      - run:
#          command: ls; build_powershell.ps1
#          shell: powershell.exe
